### ISSUE TITLE
Misleading vacuum indicators on the statusbar

### ISSUE THREAD

**Issue by dannrastor** [DESY-FH-ELab/cmstkmodlab#205]
They are a great thing, but as a person, who dropped a sensor by confusing unlabeled valves:
the color scheme for indicators seems misleading (at least for me).
Without reference, I would interpret green as "on" and red as "off".
I understand that it matches color scheme of text plates in the HW/Control tab, but there it is doubled with text.

Suggestion:
- replace with plain text
- or with colored text (in this case I think color scheme is fine)

**Comment by schuetzepaul** [comment]
Thanks @dannrastor , I understand that, my first impression was the same, but I believe you would get used to it quite quickly. In the end, the red indicator shows you "Careful, don't intervene". However, I spent 5 minutes to do this:
![Screenshot from 2024-01-31 15-06-38](https://github.com/DESY-FH-ELab/cmstkmodlab/assets/9463445/3db38bba-a825-4e50-a497-b9b868d195bd)

Do you consider this a better option?

**Comment by dannrastor** [comment]
@schuetzepaul 
IMO this is much better, thanks 
Though maybe it's not as neat as original "LEDs", but probably safer

**Comment by dannrastor** [comment]
Another option would be to keep just LEDs, but change colors from green/red to none/red
